// One review record per Item. Context/attribute reviews are never mislabeled sprites.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{Canvas}=require('skia-canvas');
const {render,makeWav,M,W,H,FPS}=require('./render_current');
const ROOT=path.resolve(__dirname,'../..'),ep=path.join(ROOT,'episodes/frankenstein-prototype');
const read=f=>JSON.parse(fs.readFileSync(path.join(ep,f)));const inv=read('item_inventory.json'),dec=read('asset_decisions.json'),sr=read('source_registry.json');
const out=path.resolve(process.env.REVIEW_OUTPUT_DIR||path.join(__dirname,'review-output'));
const starts={};let st=0;for(const sh of M.shots){starts[sh.id]=st;st+=sh.duration}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attribute=new Set(['living_engraving_palette','engraving_hatching']);const composition=new Set(['creation_chamber_composition','first_eye_shadow_mask','victor_silhouette']);const motion=new Set(['exterior_camera_push','creation_camera_drift','creature_rise_motion','victor_recoil_pose','lightning_cut','shadow_cut']);
const audio=new Set(['audio_low_drone','audio_noise_roomtone','thunder_cues','footstep_cues','electrical_crackle_audio','arc_hit_audio','victor_breath','creature_heartbeat','rain_patter_audio']);
function bounds(c){const a=c.getContext('2d').getImageData(0,0,W,H).data;let l=W,t=H,r=-1,b=-1,n=0;for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(a[(y*W+x)*4+3]>2){n++;l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}return n?{x:Math.max(0,l-12),y:Math.max(0,t-12),w:Math.min(W,r+13)-Math.max(0,l-12),h:Math.min(H,b+13)-Math.max(0,t-12),pixels:n}:null}
async function still(f,file,id=null){const c=new Canvas(W,H);render(c.getContext('2d'),f/FPS,id);await c.toFile(path.join(out,file));return c}
async function main(){fs.mkdirSync(out,{recursive:true});const rows=[],cards=[],contexts={};
for(const sh of M.shots)contexts[sh.id]=await still(Math.round((starts[sh.id]+sh.duration*.55)*FPS),`shot-${sh.id}.png`);
const sheet=new Canvas(960,846),sc=sheet.getContext('2d');sc.fillStyle='#101a12';sc.fillRect(0,0,960,846);M.shots.forEach((s,i)=>{const x=i%2*480,y=Math.floor(i/2)*282;sc.drawImage(contexts[s.id],x,y,480,270);sc.fillStyle='#d1c7a9';sc.font='11px "EB Garamond"';sc.fillText(s.id.replaceAll('_',' '),x+10,y+280)});await sheet.toFile(path.join(out,'contact-sheet.jpg'));
for(const item of inv.items){const d=dec.decisions.find(d=>d.item_id===item.id),row={item_id:item.id,importance:item.importance,status:item.status,active:item.active!==false,approval:false};let media='';
if(!row.active){row.review_mode='RETIRED';media='<p>Removed: '+esc(item.replacement_note||d.why_selected_or_pending)+'</p>'}
else if(audio.has(item.id)){row.review_mode='AUDIO_STEM';row.file=item.id+'.wav';makeWav(path.join(out,row.file),item.id);media=`<audio controls preload="none" src="${row.file}"></audio>`;row.listening_status='NOT_FINAL_APPROVED'}
else if(attribute.has(item.id)||composition.has(item.id)||motion.has(item.id)||item.id==='city_window_pattern'){
row.review_mode=motion.has(item.id)?'MOTION_SEQUENCE':item.id==='city_window_pattern'?'INTEGRATED_SOURCE_DETAIL':attribute.has(item.id)?'STYLE_CONTEXT':'COMPOSITION_CONTEXT';const reviewShot=item.id==='victor_recoil_pose'?'recoil_tableau':item.id==='engraving_hatching'?'victor_at_door':item.shot_ids[0];const sh=M.shots.find(s=>s.id===reviewShot);row.shot_id=sh.id;row.start_frame=Math.round(starts[sh.id]*FPS);row.end_frame=Math.round((starts[sh.id]+sh.duration)*FPS)-1;row.files=[];
for(const [tag,f]of[['start',row.start_frame+2],['end',row.end_frame-2]]){const file=item.id+'-'+tag+'.png';await still(f,file);row.files.push(file)}media=row.files.map(f=>`<a href="${f}"><img src="${f}" loading="lazy" alt="${esc(item.id)} context"></a>`).join('');row.limit='Context/attribute inspection, not a separated pixel layer.';
if(row.review_mode==='MOTION_SEQUENCE')media+=`<p><a href="../frankenstein_v5_3.mp4#t=${starts[sh.id]},${starts[sh.id]+sh.duration}">Inspect film segment ${starts[sh.id].toFixed(2)}–${(starts[sh.id]+sh.duration).toFixed(2)} s</a></p>`;
}else{row.review_mode='ISOLATED_LAYER';let found;
for(const sid of item.shot_ids){const sh=M.shots.find(s=>s.id===sid);if(!sh)continue;const phases=[.55,.85,.95,.99];if(item.id==='electric_arc')phases.unshift(1.34/sh.duration);if(item.id==='exterior_lightning')phases.unshift(1.05/sh.duration);for(const u of phases){const f=Math.round((starts[sid]+sh.duration*u)*FPS),c=new Canvas(W,H);render(c.getContext('2d'),f/FPS,item.id);const b=bounds(c);if(b){found={c,b,f,sid};break}}if(found)break}
if(!found)throw Error(`Active Item ${item.id} has no diagnostic pixels; fix mapping or classify its review mode.`);
const {c,b,f,sid}=found;Object.assign(row,{shot_id:sid,frame:f,time_seconds:f/FPS,bounds:b,isolated_file:item.id+'-isolated.png',context_file:item.id+'-context.png'});const crop=new Canvas(b.w,b.h);crop.getContext('2d').drawImage(c,b.x,b.y,b.w,b.h,0,0,b.w,b.h);await crop.toFile(path.join(out,row.isolated_file));const context=new Canvas(W,H),ct=context.getContext('2d');render(ct,f/FPS);ct.strokeStyle='#d2b76b';ct.lineWidth=2;ct.strokeRect(b.x,b.y,b.w,b.h);await context.toFile(path.join(out,row.context_file));media=`<div class="pair"><a class="checker" href="${row.isolated_file}"><img src="${row.isolated_file}" loading="lazy" alt="${esc(item.id)} isolated"></a><a href="${row.context_file}"><img src="${row.context_file}" loading="lazy" alt="${esc(item.id)} in shot"></a></div>`;
}
row.source_ids=item.source_ids;row.remaining_risk=d.remaining_risk;rows.push(row);
const req=Object.entries(item.requirements).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${v.map(esc).join('<br>')}</dd>`).join('');const refs=item.source_ids.map(id=>{const s=sr.sources.find(s=>s.id===id);return `<li><a href="${esc(s.url)}">${esc(id+': '+s.title)}</a> — ${esc(s.rights.commercial_asset_use)}</li>`}).join('');
cards.push(`<article id="${item.id}" data-tier="${item.importance}"><h2>${esc(item.id.replaceAll('_',' '))}</h2><small>${item.importance} · ${row.review_mode} · ${item.status}</small><p>${esc(item.purpose)}</p>${media}<details><summary>Requirements, candidates, sources and remaining work</summary><dl>${req}</dl><h3>Candidate comparison</h3><ul>${d.candidates.map(c=>`<li><b>${esc(c.candidate_id)}</b> · ${esc(c.status)}: ${esc(c.reason)}</li>`).join('')||'<li>Comparison pending.</li>'}</ul><p>${esc(d.why_selected_or_pending)}</p><p class="risk">${esc(d.remaining_risk)}</p><ul>${refs||'<li>No external source yet; reference gap remains.</li>'}</ul></details></article>`);
}
const summary={version:'5.3',renderer_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'render_current.js'))).digest('hex'),manifest_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'scene_manifest.json'))).digest('hex'),items:rows,final_approval:false,review_limit:'Generated diagnostics and implementation observations. No subjective final scores asserted.'};fs.writeFileSync(path.join(out,'review-summary.json'),JSON.stringify(summary,null,2)+'\n');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Living Engraving V5.3 — Every Item</title><style>body{background:#111911;color:#ccc2a8;font:16px/1.5 system-ui;margin:0 auto;max-width:1180px;padding:32px}h1,h2,h3{font-family:Georgia,serif;color:#eadcc0}h1{font-size:42px}h2{margin:0;font-size:24px}a{color:#d8bd7c}small{color:#b4b497}article{border-top:1px solid #55604a;padding:28px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}img{max-width:100%;max-height:320px;object-fit:contain;display:block;margin:auto}.checker{background:repeating-conic-gradient(#273129 0% 25%,#1b241d 0% 50%) 50%/16px 16px}.risk{border-left:3px solid #b2a066;padding:10px}details{margin-top:16px}summary{cursor:pointer}dt{font-weight:bold}dd{margin:0 0 12px}input,select{padding:12px;background:#223126;color:#e0d7bf;border:1px solid #6b775f;margin:6px 10px 12px 0}nav{position:sticky;top:0;background:#111911;padding:12px 0;z-index:1}audio{width:100%}@media(max-width:700px){.pair{grid-template-columns:1fr}body{padding:16px}}</style><h1>Every item earns its place.</h1><p>Frankenstein V5.3 · ${rows.length} records · ${rows.filter(i=>i.active).length} active · prototype, not final approved.</p><p>Independent layers have transparent crops and marked shot context. Baked source details, style and composition have context reviews. Motion has start/end frames and film segments; audio has solo stems. Retired items are labelled.</p><nav><input id="query" placeholder="Find an item, requirement or source"><select id="tier"><option value="">All priorities</option>${['HERO','PRIMARY','SUPPORT','ATMOSPHERIC'].map(t=>`<option>${t}</option>`).join('')}</select><span id="count"></span></nav><a href="contact-sheet.jpg">Six-shot contact sheet</a>${cards.join('')}<script>const q=document.querySelector('#query'),tier=document.querySelector('#tier');function filter(){let n=0;document.querySelectorAll('article').forEach(a=>{const show=(!tier.value||a.dataset.tier===tier.value)&&a.textContent.toLowerCase().includes(q.value.toLowerCase());a.hidden=!show;n+=show});document.querySelector('#count').textContent=n+' items'}q.addEventListener('input',filter);tier.addEventListener('change',filter);filter();</script></html>`);
console.log(`REVIEW COMPLETE: ${rows.length} Items, ${rows.filter(i=>i.active).length} active -> ${out}`)
}main().catch(e=>{console.error(e);process.exit(1)});
